### ISSUE TITLE
should R packages be installed through a Makefile as well?

### ISSUE THREAD

**Issue by magnusmunch** [rr-mrc-bsu/build-automation-example#1]
Just wondering what would is considered good practice. Is it ok to install a package through a Makefile or is that considered rude?

**Comment by kkmann** [comment]
Short answer: yes, don't do that. You are probably familiar with the ./configure - make - make install process for compiling software from source on unix systems. Typically, ./configure gets your dependencies, make only works in the current directory, and make install puts everything in the right place.

Details: https://thoughtbot.com/blog/the-magic-behind-configure-make-make-install

When using make for managing analyses, one should never install software, ever! All dependency management should be taken care of by putting the entire computing environment in a container. 
Easy, reliable, fast, no interaction required, also works on an HPC ;)
